### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by VSchlattinger**
I added the typings file index.d.ts for typescript support. I used the index.d.ts file from https://github.com/daniel-lundin/react-dom-confetti for reference and added the `random` attribute to the config type.

### CODE REVIEW

**Comment by daniel-lundin** [comment]
Cheers!

**Comment by stephenmathieson** [comment]
Any chance you could publish this to npm?

**Comment by daniel-lundin** [comment]
Sorry, forgot. Just released it.

**Comment by stephenmathieson** [comment]
Thanks Daniel!

**Pull request merged**
