### PR TITLE
Add README.md and repository field

### PR DESCRIPTION
**Pull request by marijnh**
Hi. I was hoping to use this package in a workshop about NPM, but I kind of need it to contain documentation for that, so I added a readme. If you merge this, I'd very much appreciate it if you also published a new version to NPM.

### CODE REVIEW

**Comment by marijnh** [comment]
Hello. The workshop is coming closer, and it'd be really great if the package had a readme on NPM then. I based the file on react-dom-confetti's readme, so the structure and content is likely uncontroversial.

**Comment by marijnh** [comment]
Hi, friendly ping again 🙋 -- if you could find the time to hit the merge button and shoot out a release, that'd be really great.

**Comment by daniel-lundin** [comment]
Hi, so sorry. Totally missed this somehow. :(
Will merge as soon as I'm in front of a computer.

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
